[theme]
primaryColor = "#4CAF50"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableXsrfProtection = false
enableCORS = false

[client]
# Path to your favicon file
favicon = "favicon.png"   # or .ico
